// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFMB.DAL;

#nullable disable

namespace SFMB.DAL.Migrations
{
    [DbContext(typeof(SfmbDbContext))]
    [Migration("20251111193830_InitialPostgreSqlMigration")]
    partial class InitialPostgreSqlMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SFMB.DAL.Entities.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("OperationTypeId")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.HasIndex("OperationTypeId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            OperationId = 1,
                            Amount = 40000m,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Monthly job income",
                            OperationTypeId = 1
                        },
                        new
                        {
                            OperationId = 2,
                            Amount = 220.50m,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "food",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 3,
                            Amount = 554.70m,
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "electricity, water",
                            OperationTypeId = 4
                        },
                        new
                        {
                            OperationId = 4,
                            Amount = 358m,
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "netflix",
                            OperationTypeId = 5
                        },
                        new
                        {
                            OperationId = 5,
                            Amount = 16350m,
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "apartment rent",
                            OperationTypeId = 7
                        },
                        new
                        {
                            OperationId = 6,
                            Amount = 1020.80m,
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "market",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 7,
                            Amount = 4000m,
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "consulting",
                            OperationTypeId = 2
                        },
                        new
                        {
                            OperationId = 8,
                            Amount = 820m,
                            Date = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "",
                            OperationTypeId = 5
                        },
                        new
                        {
                            OperationId = 9,
                            Amount = 325m,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "pizza",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 10,
                            Amount = 120m,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "deposit percentage",
                            OperationTypeId = 6
                        },
                        new
                        {
                            OperationId = 11,
                            Amount = 780m,
                            Date = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "food delivery",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 12,
                            Amount = 535m,
                            Date = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "lunch",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 13,
                            Amount = 370m,
                            Date = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "market",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 14,
                            Amount = 400m,
                            Date = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "bike rent",
                            OperationTypeId = 5
                        },
                        new
                        {
                            OperationId = 15,
                            Amount = 520m,
                            Date = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "street food",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 16,
                            Amount = 250.72m,
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "gas",
                            OperationTypeId = 4
                        },
                        new
                        {
                            OperationId = 17,
                            Amount = 10m,
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "matches",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 18,
                            Amount = 100m,
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "market",
                            OperationTypeId = 3
                        },
                        new
                        {
                            OperationId = 19,
                            Amount = 155m,
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "youtube subscription",
                            OperationTypeId = 5
                        },
                        new
                        {
                            OperationId = 20,
                            Amount = 2500m,
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "bonus",
                            OperationTypeId = 1
                        });
                });

            modelBuilder.Entity("SFMB.DAL.Entities.OperationType", b =>
                {
                    b.Property<int>("OperationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("OperationTypeId");

                    b.ToTable("OperationTypes");

                    b.HasData(
                        new
                        {
                            OperationTypeId = 1,
                            Description = "Monthly job income",
                            IsIncome = true,
                            Name = "Salary"
                        },
                        new
                        {
                            OperationTypeId = 2,
                            Description = "Freelance or side project payments",
                            IsIncome = true,
                            Name = "Freelance"
                        },
                        new
                        {
                            OperationTypeId = 3,
                            Description = "Daily food and household shopping",
                            IsIncome = false,
                            Name = "Groceries"
                        },
                        new
                        {
                            OperationTypeId = 4,
                            Description = "Electricity, water, gas, etc.",
                            IsIncome = false,
                            Name = "Utilities"
                        },
                        new
                        {
                            OperationTypeId = 5,
                            Description = "Movies, games, subscriptions",
                            IsIncome = false,
                            Name = "Entertainment"
                        },
                        new
                        {
                            OperationTypeId = 6,
                            Description = "Dividends or capital gains",
                            IsIncome = true,
                            Name = "Investment Return"
                        },
                        new
                        {
                            OperationTypeId = 7,
                            Description = "Monthly house or apartment rent",
                            IsIncome = false,
                            Name = "Rent"
                        });
                });

            modelBuilder.Entity("SFMB.DAL.Entities.Operation", b =>
                {
                    b.HasOne("SFMB.DAL.Entities.OperationType", "OperationType")
                        .WithMany("Operations")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationType");
                });

            modelBuilder.Entity("SFMB.DAL.Entities.OperationType", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
